project(Stubs)
cmake_minimum_required(VERSION 2.8)

enable_language(C)

SET (TMP1 ${CMAKE_RUNTIME_OUTPUT_DIRECTORY}) 
SET (TMP2 ${CMAKE_ARCHIVE_OUTPUT_DIRECTORY})
SET (TMP3 ${CMAKE_LIBRARY_OUTPUT_DIRECTORY})

SET (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TMP1}) 
SET (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${TMP2}/stubs)
SET (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${TMP3}/stubs)

add_subdirectory(HPE1472)
add_subdirectory(OMNIBUSBOX)
add_subdirectory(UNADS128)
add_subdirectory(UNFOI)
add_subdirectory(UNIS4)
add_subdirectory(UNKP50)
add_subdirectory(UNMBASE)
add_subdirectory(UNMBKOI)
add_subdirectory(UNMBKUPI)
add_subdirectory(UNMDS32)
add_subdirectory(UNMFSK24)
add_subdirectory(UNMKPRM)
add_subdirectory(UNMN3I)
add_subdirectory(UNMN8I)
add_subdirectory(UNMOSC5)
add_subdirectory(UNMS)
add_subdirectory(UNMT8K4L)
add_subdirectory(UNOLS)
add_subdirectory(UNRFSW)
add_subdirectory(UNVVK4)
add_subdirectory(UNRBSTD)
add_subdirectory(Visa)
add_subdirectory(VTVM6068)
add_subdirectory(NRPZ_stub)
add_subdirectory(SCHWARZ_stub)
add_subdirectory(TEST1003)
add_subdirectory(UNMVI102)

SET (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${TMP1}) 
SET (CMAKE_ARCHIVE_OUTPUT_DIRECTORY ${TMP2})
SET (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${TMP3})